In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import datetime as dt
%matplotlib inline

Importing each year of AirBnB Data. Unfortunately the data for listings is separate from their calendar of availability. Each year will have to be imported and then merged with dates based on listing 'ID' and 'date'. Also, there is some missing dates that will have to be taken into account later.

In [77]:
#open all data CSVs
listings2015 = pd.read_csv('listings03102015.csv')
listings2017 = pd.read_csv('listings10032017.csv')
listings2018 = pd.read_csv('listings15042018.csv')
listings2019 = pd.read_csv('listings15042019.csv')
listings2020 = pd.read_csv('listings21042020.csv')
calendar2015 = pd.read_csv('calendar03102015.csv')
calendar2017 = pd.read_csv('calendar10032017.csv')
calendar2018 = pd.read_csv('calendar15042018.csv')
calendar2019 = pd.read_csv('calendar15042019.csv')
calendar2020 = pd.read_csv('calendar21042020.csv')

In [78]:
#renaming 'listing_id' column to 'id' so that they can be merged with their respective listings. 
calendar2015.rename(columns={'listing_id':'id'}, inplace=True)
calendar2017.rename(columns={'listing_id':'id'}, inplace=True)
calendar2018.rename(columns={'listing_id':'id'}, inplace=True)
calendar2019.rename(columns={'listing_id':'id'}, inplace=True)
calendar2020.rename(columns={'listing_id':'id'}, inplace=True)

In [79]:
#merging each listing with their respective availability dates in a one year period. So, for each dataframe, multiplying the 
#amount of rental units X 365 days. 
data2015 = pd.merge(listings2015, calendar2015, on=['id'])
data2017 = pd.merge(listings2017, calendar2017, on=['id'])
data2018 = pd.merge(listings2018, calendar2018, on=['id'])
data2019 = pd.merge(listings2019, calendar2019, on=['id'])
data2020 = pd.merge(listings2020, calendar2020, on=['id'])

In [81]:
# OK... so every year AirBnb adds more columns to this data. Here we are deleting those unnecessary columns so that
# hopefully my computer doesn't explode when I try to combine them all into one big dataframe. 
cols2015 = [1,3,6,7,10,11,12,13,14,15,18]
data2015.drop(data2015.columns[cols2015],axis=1,inplace=True)
cols2017 = [1,3,6,7,10,11,12,13,14,15,18]
data2017.drop(data2017.columns[cols2017],axis=1,inplace=True)
cols2018 = [1,3,6,7,10,11,12,13,14,15,18]
data2018.drop(data2018.columns[cols2018],axis=1,inplace=True)
cols2019 = [1,3,6,7,10,11,12,13,14,15,18,19,20,21]
data2019.drop(data2019.columns[cols2019],axis=1,inplace=True)
cols2020 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,39,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,108,109,110,111]
data2020.drop(data2020.columns[cols2020],axis=1,inplace=True)

In [83]:
#renaming columns to match
data2020.rename(columns={'neighbourhood_group_cleansed':'neighbourhood_group'}, inplace=True)

In [97]:
#rearranging the order of columns in data2020 to match the others
data2020 = data2020[['id','host_id','neighbourhood_group','neighbourhood','room_type','price_x','date','available']]

In [106]:
#changing dtype of 'price' in data2020 to int
data2020['price_x'] = pd.to_numeric(data2020['price_x'])

ValueError: Unable to parse string "$433.00" at position 0

In [85]:
#Saving each dataframe as a cleaned CSV for later use
data2015.to_csv('data2015.csv')
data2017.to_csv('data2017.csv')
data2018.to_csv('data2018.csv')
data2019.to_csv('data2019.csv')
data2020.to_csv('data2020.csv')

In [98]:
data2015.info()
data2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1358895 entries, 0 to 1358894
Data columns (total 8 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   id                   1358895 non-null  int64
 1   host_id              1358895 non-null  int64
 2   neighbourhood_group  0 non-null        float64
 3   neighbourhood        1358895 non-null  object
 4   room_type            1358895 non-null  object
 5   price_x              1358895 non-null  int64
 6   date                 1358895 non-null  object
 7   available            1358895 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 93.3+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 3410155 entries, 0 to 3410154
Data columns (total 8 columns):
 #   Column               Dtype
---  ------               -----
 0   id                   int64
 1   host_id              int64
 2   neighbourhood_group  float64
 3   neighbourhood        object
 4   room_type            object
 5   price_x              object
 6   date                 object
 7   available            object
dtypes: float64(1), int64(2), object(5)
memory usage: 234.2+ MB

In [94]:
files = ['data2015.csv', 'data2017.csv', 'data2018.csv', 'data2019.csv', 'data2020.csv']
final_headers = ['id', 'host_id', 'neighbourhood_group', 'neighbourhood', 'room_type', 'price_x', 'date', 'available']

merged_rows = set()
for f in files:
    with open(f, 'rb') as csv_in:
        csvreader = pd.read_csv(csv_in, delimiter=',')
headers = dict((h, i) for i, h in enumerate(csvreader.next()))
for row in csvreader:
    merged_rows.add(tuple(row[headers[x]] for x in final_headers))
with open('output.csv', 'wb') as csv_out:
    csvwriter = csv.writer(csv_out, delimiter=',')
csvwriter.writerows(merged_rows)

AttributeError: 'DataFrame' object has no attribute 'next'

In [33]:
neighbourhoodsdf = pd.read_csv('neighborhoods.csv')
print(neighbourhoodsdf)

    neighbourhood_group                                      neighbourhood
0                   NaN               Brightwood Park, Crestwood, Petworth
1                   NaN                      Brookland, Brentwood, Langdon
2                   NaN                         Capitol Hill, Lincoln Park
3                   NaN    Capitol View, Marshall Heights, Benning Heights
4                   NaN     Cathedral Heights, McLean Gardens, Glover Park
5                   NaN  Cleveland Park, Woodley Park, Massachusetts Av...
6                   NaN  Colonial Village, Shepherd Park, North Portal ...
7                   NaN  Columbia Heights, Mt. Pleasant, Pleasant Plain...
8                   NaN   Congress Heights, Bellevue, Washington Highlands
9                   NaN  Deanwood, Burrville, Grant Park, Lincoln Heigh...
10                  NaN                           Douglas, Shipley Terrace
11                  NaN  Downtown, Chinatown, Penn Quarters, Mount Vern...
12                  NaN         Dupont Circle, Connecticut Avenue/K Street
13                  NaN                       Eastland Gardens, Kenilworth
14                  NaN  Edgewood, Bloomingdale, Truxton Circle, Eckington
15                  NaN  Fairfax Village, Naylor Gardens, Hillcrest, Su...
16                  NaN  Friendship Heights, American University Park, ...
17                  NaN                    Georgetown, Burleith/Hillandale
18                  NaN              Hawthorne, Barnaby Woods, Chevy Chase
19                  NaN                                 Historic Anacostia
20                  NaN     Howard University, Le Droit Park, Cardozo/Shaw
21                  NaN     Ivy City, Arboretum, Trinidad, Carver Langston
22                  NaN     Kalorama Heights, Adams Morgan, Lanier Heights
23                  NaN  Lamont Riggs, Queens Chapel, Fort Totten, Plea...
24                  NaN               Mayfair, Hillbrook, Mahaning Heights
25                  NaN                          Near Southeast, Navy Yard
26                  NaN       North Cleveland Park, Forest Hills, Van Ness
27                  NaN  North Michigan Park, Michigan Park, University...
28                  NaN      River Terrace, Benning, Greenway, Dupont Park
29                  NaN                                 Shaw, Logan Circle
30                  NaN                  Sheridan, Barry Farm, Buena Vista
31                  NaN  Southwest Employment Area, Southwest/Waterfron...
32                  NaN  Spring Valley, Palisades, Wesley Heights, Foxh...
33                  NaN                     Takoma, Brightwood, Manor Park
34                  NaN  Twining, Fairlawn, Randle Highlands, Penn Bran...
35                  NaN          Union Station, Stanton Park, Kingman Park
36                  NaN                        West End, Foggy Bottom, GWU
37                  NaN  Woodland/Fort Stanton, Garfield Heights, Knox ...
38                  NaN                   Woodridge, Fort Lincoln, Gateway

In [43]:
df = pd.merge(calendardf, listingsdf, on=['id', 'date'])

NameError: name 'true' is not defined

In [44]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3410155 entries, 0 to 3410154
Data columns (total 112 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   id                                            int64
 1   date                                          object
 2   available                                     object
 3   price_x                                       object
 4   adjusted_price                                object
 5   minimum_nights_x                              float64
 6   maximum_nights_x                              float64
 7   listing_url                                   object
 8   scrape_id                                     int64
 9   last_scraped                                  object
 10  name                                          object
 11  summary                                       object
 12  space                                         object
 13  description                                   object
 14  experiences_offered                           object
 15  neighborhood_overview                         object
 16  notes                                         object
 17  transit                                       object
 18  access                                        object
 19  interaction                                   object
 20  house_rules                                   object
 21  thumbnail_url                                 float64
 22  medium_url                                    float64
 23  picture_url                                   object
 24  xl_picture_url                                float64
 25  host_id                                       int64
 26  host_url                                      object
 27  host_name                                     object
 28  host_since                                    object
 29  host_location                                 object
 30  host_about                                    object
 31  host_response_time                            object
 32  host_response_rate                            object
 33  host_acceptance_rate                          object
 34  host_is_superhost                             object
 35  host_thumbnail_url                            object
 36  host_picture_url                              object
 37  host_neighbourhood                            object
 38  host_listings_count                           float64
 39  host_total_listings_count                     float64
 40  host_verifications                            object
 41  host_has_profile_pic                          object
 42  host_identity_verified                        object
 43  street                                        object
 44  neighbourhood                                 object
 45  neighbourhood_cleansed                        object
 46  neighbourhood_group_cleansed                  float64
 47  city                                          object
 48  state                                         object
 49  zipcode                                       object
 50  market                                        object
 51  smart_location                                object
 52  country_code                                  object
 53  country                                       object
 54  latitude                                      float64
 55  longitude                                     float64
 56  is_location_exact                             object
 57  property_type                                 object
 58  room_type                                     object
 59  accommodates                                  int64
 60  bathrooms                                     float64
 61  bedrooms                                      float64
 62  beds                                          float64
 63  bed_type                                      object
 64  amenities                                     object
 65  square_feet                                   float64
 66  price_y                                       object
 67  weekly_price                                  object
 68  monthly_price                                 object
 69  security_deposit                              object
 70  cleaning_fee                                  object
 71  guests_included                               int64
 72  extra_people                                  object
 73  minimum_nights_y                              int64
 74  maximum_nights_y                              int64
 75  minimum_minimum_nights                        int64
 76  maximum_minimum_nights                        int64
 77  minimum_maximum_nights                        int64
 78  maximum_maximum_nights                        int64
 79  minimum_nights_avg_ntm                        float64
 80  maximum_nights_avg_ntm                        float64
 81  calendar_updated                              object
 82  has_availability                              object
 83  availability_30                               int64
 84  availability_60                               int64
 85  availability_90                               int64
 86  availability_365                              int64
 87  calendar_last_scraped                         object
 88  number_of_reviews                             int64
 89  number_of_reviews_ltm                         int64
 90  first_review                                  object
 91  last_review                                   object
 92  review_scores_rating                          float64
 93  review_scores_accuracy                        float64
 94  review_scores_cleanliness                     float64
 95  review_scores_checkin                         float64
 96  review_scores_communication                   float64
 97  review_scores_location                        float64
 98  review_scores_value                           float64
 99  requires_license                              object
 100 license                                       object
 101 jurisdiction_names                            object
 102 instant_bookable                              object
 103 is_business_travel_ready                      object
 104 cancellation_policy                           object
 105 require_guest_profile_picture                 object
 106 require_guest_phone_verification              object
 107 calculated_host_listings_count                int64
 108 calculated_host_listings_count_entire_homes   int64
 109 calculated_host_listings_count_private_rooms  int64
 110 calculated_host_listings_count_shared_rooms   int64
 111 reviews_per_month                             float64
dtypes: float64(24), int64(21), object(67)
memory usage: 2.9+ GB

In [46]:
df.tail()

,id,date,available,price_x,adjusted_price,minimum_nights_x,maximum_nights_x,listing_url,scrape_id,last_scraped,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
3410150,43238416,2021-04-16,t,$145.00,$145.00,1.0,1125.0,https://www.airbnb.com/rooms/43238416,20200421040120,2020-04-21,...,f,f,flexible,f,f,1,1,0,0,NaN
3410151,43238416,2021-04-17,t,$145.00,$145.00,1.0,1125.0,https://www.airbnb.com/rooms/43238416,20200421040120,2020-04-21,...,f,f,flexible,f,f,1,1,0,0,NaN
3410152,43238416,2021-04-18,t,$145.00,$145.00,1.0,1125.0,https://www.airbnb.com/rooms/43238416,20200421040120,2020-04-21,...,f,f,flexible,f,f,1,1,0,0,NaN
3410153,43238416,2021-04-19,t,$145.00,$145.00,1.0,1125.0,https://www.airbnb.com/rooms/43238416,20200421040120,2020-04-21,...,f,f,flexible,f,f,1,1,0,0,NaN
3410154,43238416,2021-04-20,t,$145.00,$145.00,1.0,1125.0,https://www.airbnb.com/rooms/43238416,20200421040120,2020-04-21,...,f,f,flexible,f,f,1,1,0,0,NaN

In [50]:
print (df.date.min())
print (df.date.max())

2020-04-21
2021-04-21

In [4]:
detailedlistings = pd.read_csv('detailed listings.csv')
detailedlistings.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9201 entries, 0 to 9200
Data columns (total 106 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   id                                            int64
 1   listing_url                                   object
 2   scrape_id                                     int64
 3   last_scraped                                  object
 4   name                                          object
 5   summary                                       object
 6   space                                         object
 7   description                                   object
 8   experiences_offered                           object
 9   neighborhood_overview                         object
 10  notes                                         object
 11  transit                                       object
 12  access                                        object
 13  interaction                                   object
 14  house_rules                                   object
 15  thumbnail_url                                 float64
 16  medium_url                                    float64
 17  picture_url                                   object
 18  xl_picture_url                                float64
 19  host_id                                       int64
 20  host_url                                      object
 21  host_name                                     object
 22  host_since                                    object
 23  host_location                                 object
 24  host_about                                    object
 25  host_response_time                            object
 26  host_response_rate                            object
 27  host_acceptance_rate                          float64
 28  host_is_superhost                             object
 29  host_thumbnail_url                            object
 30  host_picture_url                              object
 31  host_neighbourhood                            object
 32  host_listings_count                           float64
 33  host_total_listings_count                     float64
 34  host_verifications                            object
 35  host_has_profile_pic                          object
 36  host_identity_verified                        object
 37  street                                        object
 38  neighbourhood                                 object
 39  neighbourhood_cleansed                        object
 40  neighbourhood_group_cleansed                  float64
 41  city                                          object
 42  state                                         object
 43  zipcode                                       object
 44  market                                        object
 45  smart_location                                object
 46  country_code                                  object
 47  country                                       object
 48  latitude                                      float64
 49  longitude                                     float64
 50  is_location_exact                             object
 51  property_type                                 object
 52  room_type                                     object
 53  accommodates                                  int64
 54  bathrooms                                     float64
 55  bedrooms                                      float64
 56  beds                                          float64
 57  bed_type                                      object
 58  amenities                                     object
 59  square_feet                                   float64
 60  price                                         object
 61  weekly_price                                  object
 62  monthly_price                                 object
 63  security_deposit                              object
 64  cleaning_fee                                  object
 65  guests_included                               int64
 66  extra_people                                  object
 67  minimum_nights                                int64
 68  maximum_nights                                int64
 69  minimum_minimum_nights                        int64
 70  maximum_minimum_nights                        int64
 71  minimum_maximum_nights                        int64
 72  maximum_maximum_nights                        int64
 73  minimum_nights_avg_ntm                        float64
 74  maximum_nights_avg_ntm                        float64
 75  calendar_updated                              object
 76  has_availability                              object
 77  availability_30                               int64
 78  availability_60                               int64
 79  availability_90                               int64
 80  availability_365                              int64
 81  calendar_last_scraped                         object
 82  number_of_reviews                             int64
 83  number_of_reviews_ltm                         int64
 84  first_review                                  object
 85  last_review                                   object
 86  review_scores_rating                          float64
 87  review_scores_accuracy                        float64
 88  review_scores_cleanliness                     float64
 89  review_scores_checkin                         float64
 90  review_scores_communication                   float64
 91  review_scores_location                        float64
 92  review_scores_value                           float64
 93  requires_license                              object
 94  license                                       float64
 95  jurisdiction_names                            object
 96  instant_bookable                              object
 97  is_business_travel_ready                      object
 98  cancellation_policy                           object
 99  require_guest_profile_picture                 object
 100 require_guest_phone_verification              object
 101 calculated_host_listings_count                int64
 102 calculated_host_listings_count_entire_homes   int64
 103 calculated_host_listings_count_private_rooms  int64
 104 calculated_host_listings_count_shared_rooms   int64
 105 reviews_per_month                             float64
dtypes: float64(24), int64(21), object(61)
memory usage: 7.4+ MB

C:\Users\johns\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (61,62) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)